image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - cmd: npm ci

for:
  -
    on:
      APPVEYOR_REPO_TAG: true

    build_script:
    - cmd: npm run electron:release

  -
    on:
      APPVEYOR_REPO_TAG: false

      build_script:
      - cmd npm run electron:build
